---
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.3.0
    container_name: mealie
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1006
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.example.com/
      - OPENAI_BASE_URL=   # leave empty to use standard if aren't sure
      - OPENAI_API_KEY=YourAPIKEY
      - OPENAI_MODEL=gpt-4o
      - OPENAI_ENABLE_IMAGE_SERVICES=true
      - OPENAI_WORKERS=1 # more = more money
      - OPENAI_SEND_DATABASE_DATA=false  # true = more money
      - OPENAI_REQUEST_TIMEOUT=60 # default is 60

    restart: always
    volumes:
      - /docker-containers/mealie:/app/data
    stdin_open: true    # to attach to containers
    tty: true           # also used to attach to containers
#    network_mode: service:wireguard     # To run through vpn service container, in turn UI port must be forwarded inside vpn. No local access unless otherwise defined
    networks:           # Specify network for container
      - homelab
networks:    # I don't know why but you have to specify the network 2x. In service, and in this tag area..
  homelab:
    external: true      # This option causes compose to join the above network instead of making a _default one (supposedly)