---
services:
  apprise:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise
    environment:
      - PUID=1000
      - PGID=1006
      - TZ=America/New_York
      - APPRISE_ATTACH_SIZE=0 #optional
    volumes:
      - /docker-containers/apprise/config:/config
      - /docker-containers/apprise/attachments:/attachments #optional
    ports:
      - 8004:8000
    restart: unless-stopped
    stdin_open: true    # to attach to containers
    tty: true           # also used to attach to containers
#    network_mode: service:wireguard     # To run through vpn service container, in turn UI port must be forwarded inside vpn. No local access unless otherwise defined
    networks:           # Specify network for container
      - homelab
networks:    # I don't know why but you have to specify the network 2x. In service, and in this tag area..
  homelab:
    external: true      # This option causes compose to join the above network instead of making a _default one (supposedly)