version: "2.1"
services:
  readarr-audio:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr-audio
    environment:
      - PUID=1000
      - PGID=1006
      - TZ=America/New_York
    volumes:
      - /docker-containers/readarr-audio:/config
      - /Books:/books #optional
      - /unsorted:/downloads #optional
    ports:
      - 8786:8787
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - homelab
networks:
  homelab:
    name: homelab
    external: true      # This option causes compose to join the above network instead of making a _default one