services:
  vocechat-server:
    image: privoce/vocechat-server:latest
    container_name: vocechat-server
    restart: always
    ports:
      - 3101:3000
    environment:
      - PUID=1000
      - PGID=1006
    volumes:
      - /docker-containers/vocechat/data:/home/vocechat-server/data
#    network_mode: service:wireguard     # To run through vpn service container, in turn UI port must be forwarded inside vpn. No local access unless otherwise defined
    networks:           # Specify network for container
      - homelab
networks:    # I don't know why but you have to specify the network 2x. In service, and in this tag area..
  homelab:
    external: true      # This option causes compose to join the above network instead of making a _default one (supposedly)